### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by deanfourie1** [Onemind-Services-LLC/netbox-secrets#112] opened 2023-11-29 11:21 UTC
### NetBox Secrets plugin version

v1.9.0

### NetBox version

v3.6.4

### Steps to Reproduce

Created a public/private key and added secrets.

### Expected Behavior

able to unlock secret when logged in, without the need to enter the private key.

### Observed Behavior

Every time I try unlock a secret, I am prompted to enter the private key.
![Screenshot 2023-11-30 002015](https://github.com/Onemind-Services-LLC/netbox-secrets/assets/71812804/7a83ff1f-3f50-40f4-a35c-9eebb187a980)

**Comment by deanfourie1** [comment] 2023-11-29 11:23
![Screenshot 2023-11-30 002215](https://github.com/Onemind-Services-LLC/netbox-secrets/assets/71812804/45caabfe-b53f-447c-8863-61b1a9c87de9)

**Comment by deanfourie1** [comment] 2023-11-29 11:23
![Screenshot 2023-11-30 002231](https://github.com/Onemind-Services-LLC/netbox-secrets/assets/71812804/20b3775f-d508-4363-8c24-a16bfe543ee1)

**Comment by abhi1693** [comment] 2023-11-30 07:48
Thank you for opening a bug report. I was unable to reproduce the reported behavior on NetBox v3.6.4. Please re-confirm the reported behavior on the current stable release and adjust your post above as necessary. Remember to provide detailed steps that someone else can follow using a clean installation of NetBox to reproduce the issue. Remember to include the steps taken to create any initial objects or other data.

**Comment by abhi1693** [comment] 2024-01-01 06:30
I'm closing this due to no update has been provided.

**Closed by abhi1693** 2024-01-01 06:30 UTC
Labels: type: bug
